training:
  curriculum:
    learning_rate: 
      start: 0.00005
      end: 0.0
      interval: 100
      increment: 0.00001
      begin_curr: 0 #want to scale down for last 20$ of training
    sparsity_penalty:
      start: 0.0
      end: 5.0
      interval: 100
      increment: 0.1
      begin_curr: 0 #want to scale up for first 5% of training
  save_every_step: 1000
  keep_every_steps: 1000
  test_run: False
out_dir: c-sae/output/c-sae_test
target_layer: features.2
wandb:
  log_every_steps: 10
name: c-sae_test
dict_factor: 16.0